<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="qa-akotkar" name="com.crmapplication.qa.testcases.ContactPagetest" tests="3" failures="1" timestamp="22 Apr 2020 03:40:34 GMT" time="103.006" errors="0">
  <testcase name="verifyContactPageTitleTest" time="33.152" classname="com.crmapplication.qa.testcases.ContactPagetest">
    <failure type="java.lang.AssertionError" message="expected [wrong title] but found [Cogmento CRM]">
      <![CDATA[java.lang.AssertionError: expected [wrong title] but found [Cogmento CRM]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crmapplication.qa.testcases.ContactPagetest.verifyContactPageTitleTest(ContactPagetest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyContactPageTitleTest -->
  <testcase name="VerifyContactURLTest" time="24.403" classname="com.crmapplication.qa.testcases.ContactPagetest"/>
  <testcase name="verifyContactCheckTest" time="45.451" classname="com.crmapplication.qa.testcases.ContactPagetest"/>
</testsuite> <!-- com.crmapplication.qa.testcases.ContactPagetest -->
